name: ZIG TEST CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Zig
    - uses: goto-bus-stop/setup-zig@v2.2.0  
    - name: configure
      run: zig build test
